Set desired glib min/max API versions
Setting GLIB_VERSION_MAX_ALLOWED ensures we get warnings if
we use APIs that are newer than our declared minimum glib
version.

Setting GLIB_VERSION_MIN_REQUIRED ensures that we get
warnings if we use APIs deprecated in versions preceeding
this.

If the latter is omitted then we get warnings for all
deprecations in glib, which is undesirable if we want to
keep compat with older versions.

This avoids a build error with latest glib

../../libvirt-sandbox/libvirt-sandbox-config.c: In function ‘gvir_sandbox_config_init’:
../../libvirt-sandbox/libvirt-sandbox-config.c:483:13: error: G_ADD_PRIVATE [-Werror]
  483 |     priv = config->priv = GVIR_SANDBOX_CONFIG_GET_PRIVATE(config);
      |             ^~~~~~~~~~~~~~~

Caused by G_TYPE_INSTANCE_GET_PRIVATE being deprecated.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>