build: don't set glib version constraints for g-ir-scanner
The g-ir-scanner CFLAGS are duplicated from the libvirt-sandbox.la
CFLAGS. On the surface it sounds fine to use this for setting

  -DGLIB_VERSION_MIN_REQUIRED=VER
  -DGLIB_VERSION_MAX_ALLOWED=VER

as we want all our code to be constrained by these declared glib
versions to prevent us accidentally using APIS from newer glib by
mistake.

A subtle problem was revealed with the arrival of gobject-introspection
version 1.70.  The g-ir-scanner program auto-generates some glib code
for handling introspection, and this generated code uses glib APIs that
are newer than our declared version and this triggers compile failures

/builds/libvirt/libvirt-sandbox/build/libvirt-sandbox/tmp-introspectxuajrl_2/LibvirtSandbox-1.0.c:251:3: error: ‘G_TYPE_FLAG_FINAL’ is deprecated: Not available before 2.70 [-Werror=deprecated-declarations]
  251 |   if (G_TYPE_IS_FINAL (type))
      |   ^~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /builds/libvirt/libvirt-sandbox/build/libvirt-sandbox/tmp-introspectxuajrl_2/LibvirtSandbox-1.0.c:30:
/usr/include/glib-2.0/gobject/gtype.h:1050:3: note: declared here
 1050 |   G_TYPE_FLAG_FINAL GLIB_AVAILABLE_ENUMERATOR_IN_2_70 = (1 << 6)
      |   ^~~~~~~~~~~~~~~~~

This is actually harmless, because systems with an older glib will also
have older g-ir-scanner and thus not be using these new APIs.

We need to exclude the glib version constraints from code generated by
glib tools, and thus means we have to be more careful about setting
cflags for g-ir-scanner.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>